service: researchpal-api

custom:
  settings:
    POSTS_TABLE: researchpal-posts

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}"

functions:
  makePost:
    handler: handler.makePost
    events:
    - http:
        path: /post
        method: post
        cors: true
  getAllPosts:
    handler: handler.getAllPosts
    events:
      - http:
          path: /posts
          method: get
          cors: true
  getSinglePost:
    handler: handler.getSinglePost
    events:
      - http:
          path: /singlepost/{uid}
          method: get
          cors: true
  getPostByUser:
    handler: handler.getPostByUser
    events:
      - http:
          path: /poste/{uid}
          method: get
          cors: true
  updatePost:
    handler: handler.updatePost
    events:
      - http:
          path: /post/{id}
          method: put
          cors: true 
  deletePost:
    handler: handler.deletePost
    events:
      - http:
          path: /post/{id}
          method: delete
          cors: true 

resources:
  Resources:
    PostTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "uid"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "uid"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}






